### ISSUE TITLE
Update to follow Best Practices

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/shipitscript#43]
- [x] Use Docker & Docker Compose for running a local dev environment, based on the python:3 image
- [x] Use pip-compile-multi, and Pyup.io for dependency management
  - See https://github.com/mozilla-releng/releng-rfcs/blob/master/rfcs/0022-app-best-practices.md#dependency-management for requirements file details.
- [x] Use tox as a test runner
- [x] Use Taskcluster for CI
- [x] Ensure production pushes happen manually, in response to bugs filed
- [x] Ensure stage pushes happen in response to tags on Dockerhub

(Remove items that are not applicable to this project).

**Comment by garbas** [comment]
in scriptworker case docker compose is not really needed since there is only one docker instance and if this is true then we can close this issue

**Comment by mozbhearsum** [comment]
The other nice convenience of docker-compose is that you can set default env vars, ports, etc. Without it, you either need longer "docker run" commands, or some sort of other wrapper to set them.

Whatever you want to do is fine, just wanted to make note of that.

**Comment by garbas** [comment]
@mozbhearsum i'd actually welcome your suggestion with docker-compose since i don't know it in details.

scriptworkers don't require no env variables since it is a cli utility. you want to use dockerfile only to have access to development environment. For now I'm using this command to enter the development environment:

```console
docker run --rm -v it $(docker build -q .) /bin/bash
```

would docker-compose improve on this?

**Comment by mozbhearsum** [comment]
Personally, I think "docker-compose up" is simpler than the above command. If it were me, I'd use it instead of requiring developers to know or copy/paste the command above.

**Comment by garbas** [comment]
i looked closed at docker compose and i found that there is a tty option. i guess it wouldn't hurt to add docker-compose.yml.

you'd have to run 2 commands to enter the development environment:
```
% docker-compose up -d
% docker-compose exec cli bash
```

i'll add this later this week and i'm repoening this to reming me

**Comment by rail** [comment]
All done here
